[package]
name = "actix-gcd"
version = "0.1.0"
authors = ["Providence Salumu <Providence.Salumu@smunix.com>"]
edition = "2021"

[dependencies]
actix-web = "4.8.0"
serde = { version = "1.0.203", feature = ["derive"] }
